import Head from "next/head";
import Link from "next/link";
import Footer from "~/components/Footer";
import Hero from "~/components/Hero";
import Navigation from "~/components/Navigation";
import VisionMap from "~/components/VisionMap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vision Maps</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Navigation />
          <Hero />
          <Footer />
        </div>
      </main>
    </>
  );
}
